export const RESEARCH_LIMITS = {
  MAX_QUERIES: 10,
  MIN_QUERIES: 6,
  MAX_SOURCES: 6,
  MIN_SOURCE_RELEVANCE: 0.35,
  MAX_CLAIMS: 12,
  MAX_HIGH_IMPORTANCE_CLAIMS_TO_VERIFY: 4,
};

export const SOURCE_TIER_WEIGHTS = {
  1: 1,
  2: 0.75,
  3: 0.15,
} as const;

export const UNKNOWN_SOURCE_WEIGHT = 0.5;

export const QUALITY_BANDS = {
  FULL: 90,
  VERIFIED_ONLY: 75,
  RETRY: 50,
} as const;

export const FRESHNESS_MS = {
  breaking: 12 * 60 * 60 * 1000,
  active_trend: 3 * 24 * 60 * 60 * 1000,
  seasonal: 14 * 24 * 60 * 60 * 1000,
  evergreen: 60 * 24 * 60 * 60 * 1000,
} as const;

export const ACTIVE_TREND_TYPES = [
  "sports_event",
  "music_release",
  "tour",
  "viral_moment",
  "celebrity",
] as const;

export const SEASONAL_TREND_TYPES = ["film_tv"] as const;

export const QUERY_TYPES_BY_TREND = {
  sports_event: [
    "exact_phrase",
    "entity_relationship",
    "event_context",
    "recent_news",
    "official_source",
    "season_year",
    "broader_topic",
  ],
  music_release: [
    "exact_phrase",
    "entity_relationship",
    "event_context",
    "recent_news",
    "official_source",
    "season_year",
    "broader_topic",
  ],
  tour: [
    "exact_phrase",
    "entity_relationship",
    "event_context",
    "recent_news",
    "official_source",
    "broader_topic",
  ],
  film_tv: [
    "exact_phrase",
    "entity_relationship",
    "event_context",
    "broader_topic",
  ],
  celebrity: [
    "exact_phrase",
    "entity_relationship",
    "recent_news",
    "social_viral",
    "official_source",
    "broader_topic",
  ],
  viral_moment: [
    "exact_phrase",
    "entity_relationship",
    "recent_news",
    "social_viral",
    "broader_topic",
  ],
  franchise: [
    "exact_phrase",
    "official_source",
    "broader_topic",
  ],
  brand: ["exact_phrase", "official_source", "broader_topic"],
  generic: [],
} as const;

export const GENERIC_NEWS_OUTLETS = [
  "reuters.com",
  "apnews.com",
  "bloomberg.com",
  "bbc.com",
  "bbc.co.uk",
  "cnn.com",
  "nytimes.com",
  "washingtonpost.com",
  "theguardian.com",
  "npr.org",
  "usatoday.com",
  "abcnews.go.com",
  "cbsnews.com",
  "nbcnews.com",
  "politico.com",
  "theverge.com",
  "wired.com",
  "arstechnica.com",
  "engadget.com",
  "forbes.com",
  "fortune.com",
  "businessinsider.com",
];

export const TREND_NEWS_OUTLETS = {
  sports_event: [
    "espn.com",
    "cbssports.com",
    "foxsports.com",
    "nbcsports.com",
    "sportsillustrated.com",
    "si.com",
    "sbnation.com",
    "bleacherreport.com",
    "theathletic.com",
    "skysports.com",
    "goal.com",
  ],
  music_release: [
    "billboard.com",
    "pitchfork.com",
    "consequence.net",
    "rollingstone.com",
    "complex.com",
    "hypebeast.com",
  ],
  tour: [
    "billboard.com",
    "pollstar.com",
    "consequence.net",
    "rollingstone.com",
    "variety.com",
  ],
  film_tv: [
    "variety.com",
    "hollywoodreporter.com",
    "deadline.com",
    "ew.com",
    "indiewire.com",
    "theplaylist.net",
  ],
  celebrity: ["eonline.com", "people.com", "vanityfair.com"],
  viral_moment: [],
  franchise: [],
  brand: [],
  generic: [],
} as const;

export const COMMUNITY_HOSTS = [
  "reddit.com",
  "x.com",
  "twitter.com",
  "tiktok.com",
  "facebook.com",
  "instagram.com",
  "threads.net",
  "quora.com",
  "fandom.com",
  "wikia.com",
  "tumblr.com",
  "medium.com",
  "substack.com",
  "blogspot.com",
  "wordpress.com",
  "discord.com",
  "discord.gg",
  "4chan.org",
  "youtube.com",
  "youtu.be",
  "weibo.com",
  "tieba.baidu.com",
];

export const TIER1_OFFICIAL_ROOTS = {
  sports_event: [
    "mlb.com",
    "nba.com",
    "wnba.com",
    "nfl.com",
    "nhl.com",
    "ncaa.com",
    "nascar.com",
    "mls.com",
    "nrl.com",
    "afl.com.au",
    "fifa.com",
    "uefa.com",
    "formula1.com",
    "atptour.com",
    "wtatennis.com",
    "pga.com",
    "rydercup.com",
  ],
  music_release: ["grammy.com", "riaa.com"],
  tour: [],
  film_tv: [],
  celebrity: [],
  viral_moment: [],
  franchise: [],
  brand: [],
  generic: [],
} as const;

export const OFFICIAL_HOST_MARKERS = [
  ".gov",
  ".mil",
  ".int",
  "official",
  "league",
  "association",
  "federation",
  "commission",
];

export const GENERIC_PRODUCT_TOKENS = [
  "custom",
  "name",
  "number",
  "personalized",
  "personalise",
  "personalize",
  "blank",
  "unisex",
  "men",
  "women",
  "boys",
  "girls",
  "kids",
  "adult",
  "baby",
  "short sleeve",
  "long sleeve",
  "sleeve",
  "sleeves",
  "hooded",
  "pullover",
  "size",
  "sizes",
  "small",
  "medium",
  "large",
  "xlarge",
  "pack",
  "set",
  "bundle",
  "style",
  "styles",
  "edition",
  "vintage",
  "retro",
  "classic",
  "graphic",
  "print",
  "printed",
  "design",
  "new",
  "hot",
  "sale",
  "best",
];

export const TITLE_STOPWORDS = [
  "a",
  "an",
  "the",
  "of",
  "in",
  "on",
  "to",
  "for",
  "and",
  "or",
  "with",
  "at",
  "by",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "as",
  "its",
  "from",
  "that",
  "this",
  "it",
  "has",
  "have",
  "had",
  "will",
  "s",
];

export const TWO_PART_PUBLIC_SUFFIXES = [
  "co.uk",
  "org.uk",
  "ac.uk",
  "gov.uk",
  "co.jp",
  "or.jp",
  "co.nz",
  "com.au",
  "net.au",
  "org.au",
  "com.br",
  "com.mx",
  "co.za",
  "co.in",
  "com.sg",
  "com.hk",
];
