import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import './global.css';
export const metadata: Metadata = {
  title: 'Woo!',
  description: 'Generated by deveric2k',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <meta
        name='viewport'
        content='width=device-width, initial-scale=1, maximum-scale=1'
      ></meta>
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
